# Generated by Django 4.0.3 on 2022-06-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=50, verbose_name='Nombre area')),
            ],
            options={
                'db_table': 'Area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False, verbose_name='id especialidad')),
                ('nombre_especialidad', models.CharField(max_length=50, verbose_name='nombre especialidad')),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id_especialista', models.IntegerField(primary_key=True, serialize=False)),
                ('rut_especialista', models.CharField(max_length=50, verbose_name='rut especialista')),
                ('nombre_especialista', models.CharField(max_length=50, verbose_name='nombre especialista')),
                ('apellido_especialista', models.CharField(max_length=50, verbose_name='apellido especialista')),
            ],
            options={
                'db_table': 'especialista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id_hora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaSolicitudHora',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False, verbose_name='id especialidad')),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripcion')),
                ('hora', models.TimeField(blank=True)),
                ('fecha', models.DateField()),
                ('respuesta', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'listaSolicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Papellido', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('Sapellido', models.CharField(max_length=50, null=True, verbose_name='Apellido materno')),
                ('rut', models.CharField(max_length=50, verbose_name='rut especialista')),
                ('correo', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id_rango', models.AutoField(primary_key=True, serialize=False)),
                ('rango', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'rango',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroHora',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion hora medica')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True)),
            ],
            options={
                'db_table': 'RegistroHora',
                'managed': False,
            },
        ),
    ]
