# Generated by Django 4.0.3 on 2022-06-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Papellido', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('Sapellido', models.CharField(max_length=50, null=True, verbose_name='Apellido materno')),
                ('rut', models.CharField(max_length=50, verbose_name='rut especialista')),
                ('correo', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id_alergias', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alergia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'alergias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnfermedadesCronicas',
            fields=[
                ('id_enfermedades_cronicas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_enfermedad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'enfermedadesCronica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnfermedadesTerminales',
            fields=[
                ('id_enfermedades_terminales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_enfermedad_terminal', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'enfermedadTerminales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farmaceutico',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Papellido', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('Sapellido', models.CharField(max_length=50, null=True, verbose_name='Apellido materno')),
                ('rut', models.CharField(max_length=50, verbose_name='rut especialista')),
                ('correo', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'farmaceutico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fichaMedica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'observaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Papellido', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('Sapellido', models.CharField(max_length=50, null=True, verbose_name='Apellido materno')),
                ('rut', models.CharField(max_length=50, verbose_name='rut especialista')),
                ('correo', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id_rango', models.AutoField(primary_key=True, serialize=False)),
                ('rango', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'rango',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('indicaciones', models.CharField(max_length=100)),
                ('fecha_Retiro', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('respuesta', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id_remedio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_remedio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'remedio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=50, verbose_name='Sector')),
            ],
            options={
                'db_table': 'sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo usuario')),
            ],
            options={
                'db_table': 'tipoUsuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioLogin',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
            options={
                'db_table': 'usuarioLogin',
                'managed': False,
            },
        ),
    ]
