# Generated by Django 4.0.3 on 2022-05-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False, verbose_name='id especialidad')),
                ('nombre_especialidad', models.CharField(max_length=50, verbose_name='nombre especialidad')),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id_especialista', models.AutoField(primary_key=True, serialize=False)),
                ('rut_especialista', models.CharField(max_length=50, verbose_name='rut especialista')),
                ('nombre_especialista', models.CharField(max_length=50, verbose_name='nombre especialista')),
                ('apellido_especialista', models.CharField(max_length=50, verbose_name='apellido especialista')),
            ],
            options={
                'db_table': 'especialista',
                'managed': False,
            },
        ),
    ]
